### ISSUE TITLE
v0.0.1 roadmap

### ISSUE THREAD

**Issue by mbadrala** [brushbrush/moodmood#2]
- [ ] Drag and drop image
- [ ] Write texts
- [ ] Arrange dropped items
- [ ] Save data on browser
- [ ] Change background
- [ ] Resize items
